"""
Stage 15 -- Capstone Synthesis

Recombines results already validated in Stages 1-14 into a small number
of headline summary views. Introduces NO new simulation logic and NO new
numeric claims -- every number plotted here either comes directly from a
saved results/*.csv, or (if that file happens to be missing on disk) is
regenerated by calling the EXACT SAME already-validated function the
original stage used.

Three headline slices, per the Extension Plan's synthesis scope:
    1. "Failure & Fix" decision map -- Stage 5/8's failure map, with
       Stage 6/9/14's remediation costs overlaid at the EXACT points
       where they were tested (not extrapolated across the grid).
    2. "Robustness under real-world impairments" -- Stage 13's multipath
       finding and Stage 10's noise/BER finding, side by side, showing
       the core near-field-beamforming advantage survives both.
    3. "Bug becomes feature" -- Stage 5/8's worst-loss region connected
       directly to Stage 11's best-multi-user-separation region, at
       matching (N, bandwidth, r/Rayleigh) coordinates.
"""

from __future__ import annotations

import os

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from constants import CENTER_FREQ

RESULTS_DIR = "results"
FIGURES_DIR = "figures"


# ---------------------------------------------------------------------------
# Data loading / regeneration -- robust to missing intermediate files.
# ---------------------------------------------------------------------------

def load_or_regenerate(filename: str, regenerate_fn) -> pd.DataFrame:
    """Load results/{filename} if present; otherwise call regenerate_fn()
    (which must call the SAME already-validated function the original
    stage used) and save the result for next time.
    """
    path = os.path.join(RESULTS_DIR, filename)
    if os.path.exists(path):
        return pd.read_csv(path)
    print(f"  [synthesis] {filename} not found, regenerating via original stage's function...")
    df = regenerate_fn()
    df.to_csv(path, index=False)
    return df


def _regenerate_fine_sweep() -> pd.DataFrame:
    from sweep import run_sweep
    Ns_fine = [8, 16, 32, 64, 128, 256, 512, 1024]
    bandwidths_fine = [10e6, 100e6, 400e6, 1e9, 2e9, 4e9]
    r_fracs_fine = [0.02, 0.05, 0.1, 0.2, 0.5, 1.0, 2.0, 5.0, 10.0, 20.0]
    return run_sweep(Ns_fine, bandwidths_fine, r_fracs_fine, CENTER_FREQ)


def _regenerate_stage6_recovery() -> pd.DataFrame:
    from correction import recovery_table
    return recovery_table(512, 4e9, [0.02, 0.05, 0.1], CENTER_FREQ)


def _regenerate_stage9() -> pd.DataFrame:
    raise RuntimeError(
        "stage9_quantization.csv missing and not cheap to regenerate inline -- "
        "re-run validate_stage9.py first."
    )


def _regenerate_stage10() -> pd.DataFrame:
    raise RuntimeError(
        "stage10_noise.csv missing and not cheap to regenerate inline -- "
        "re-run validate_stage10.py first."
    )


def _regenerate_stage11() -> pd.DataFrame:
    raise RuntimeError(
        "stage11_multiuser.csv missing and not cheap to regenerate inline -- "
        "re-run validate_stage11.py first."
    )


def _regenerate_stage13() -> pd.DataFrame:
    raise RuntimeError(
        "stage13_multipath.csv missing and not cheap to regenerate inline -- "
        "re-run validate_stage13.py first."
    )


def _regenerate_stage14() -> pd.DataFrame:
    raise RuntimeError(
        "stage14_hybrid.csv missing and not cheap to regenerate inline -- "
        "re-run validate_stage14.py first."
    )


def load_all_sources() -> dict:
    """Load (or regenerate) every source dataset Stage 15 draws from."""
    return {
        "fine_sweep": load_or_regenerate("fine_sweep.csv", _regenerate_fine_sweep),
        "stage6_recovery": load_or_regenerate("stage6_recovery.csv", _regenerate_stage6_recovery),
        "stage9_quantization": load_or_regenerate("stage9_quantization.csv", _regenerate_stage9),
        "stage10_noise": load_or_regenerate("stage10_noise.csv", _regenerate_stage10),
        "stage11_multiuser": load_or_regenerate("stage11_multiuser.csv", _regenerate_stage11),
        "stage13_multipath": load_or_regenerate("stage13_multipath.csv", _regenerate_stage13),
        "stage14_hybrid": load_or_regenerate("stage14_hybrid.csv", _regenerate_stage14),
    }


# ---------------------------------------------------------------------------
# Slice 1 -- Failure & Fix decision map
# ---------------------------------------------------------------------------

def classify_severity(loss_db: float) -> str:
    """Safe/Marginal/Severe bands using THIS project's own established
    thresholds: 3dB is Stage 5's failure threshold; 8dB is the coarse
    sweep's 'hardest point' reference used in Stage 5's own hard-gate
    checks. Not new/arbitrary thresholds."""
    if loss_db < 3.0:
        return "Safe"
    elif loss_db < 8.0:
        return "Marginal"
    else:
        return "Severe"


def build_decision_map(sources: dict):
    fine_sweep = sources["fine_sweep"]
    stage6 = sources["stage6_recovery"]
    stage9 = sources["stage9_quantization"]
    stage14 = sources["stage14_hybrid"]

    facet_bandwidths = [10e6, 400e6, 4e9]  # same 3 facets Stage 5/8 used
    fig, axes = plt.subplots(1, len(facet_bandwidths), figsize=(18, 6), sharey=True)

    severity_colors = {"Safe": 0, "Marginal": 1, "Severe": 2}
    cmap = plt.matplotlib.colors.ListedColormap(["#2a9d8f", "#e9c46a", "#e76f51"])

    for ax, bw in zip(axes, facet_bandwidths):
        sub = fine_sweep[fine_sweep.bandwidth == bw].copy()
        sub["severity_code"] = sub.gain_loss_conventional_db.apply(
            lambda x: severity_colors[classify_severity(x)]
        )
        pivot = sub.pivot(index="r_frac_rayleigh", columns="N", values="severity_code").sort_index()
        X = pivot.columns.values.astype(float)
        Y = pivot.index.values.astype(float)
        Z = pivot.values

        ax.pcolormesh(X, Y, Z, shading="nearest", cmap=cmap, vmin=0, vmax=2)
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.axhline(1.0, color="white", linestyle="--", linewidth=1, alpha=0.7)
        ax.set_xlabel("Array size N")
        ax.set_title(f"Bandwidth = {bw/1e6:.0f} MHz")

        # Overlay: exact tested remediation points, only at BW=4GHz where
        # Stages 6/9/14 all did their worst-region testing.
        if bw == 4e9:
            for _, row in stage6.iterrows():
                ax.plot(512, row.r_frac_rayleigh, "k^", markersize=10, markeredgecolor="white")
            ax.annotate(
                "Combined corrector:\nfull recovery\n(11.2-13.4 dB, Stage 6)",
                xy=(512, 0.05), xytext=(60, 0.015),
                fontsize=7, color="white",
                arrowprops=dict(arrowstyle="->", color="white"),
            )
            eff_2bit = stage9[(stage9.r_frac_rayleigh == 0.05) & (stage9.n_bits == 2)].iloc[0].recovery_efficiency
            ax.annotate(
                f"2-bit quantized:\n{eff_2bit*100:.0f}% recovery eff.\n(Stage 9)",
                xy=(512, 0.05), xytext=(12, 0.4),
                fontsize=7, color="white",
                arrowprops=dict(arrowstyle="->", color="white"),
            )
            loss_16rf = stage14[stage14.n_rf == 16].iloc[0].gain_loss_db
            ax.annotate(
                f"16-RF hybrid:\n{loss_16rf:.3f} dB from ideal\n(Stage 14)",
                xy=(512, 0.1), xytext=(180, 3.0),
                fontsize=7, color="white",
                arrowprops=dict(arrowstyle="->", color="white"),
            )

    axes[0].set_ylabel("Distance / Rayleigh distance")
    from matplotlib.patches import Patch
    legend_elems = [Patch(facecolor=c, label=l) for l, c in
                    zip(["Safe (<3dB)", "Marginal (3-8dB)", "Severe (>8dB)"],
                        ["#2a9d8f", "#e9c46a", "#e76f51"])]
    fig.legend(handles=legend_elems, loc="upper center", ncol=3, bbox_to_anchor=(0.5, 1.05))
    plt.suptitle(
        "Stage 15, Slice 1: Failure severity map with validated fixes overlaid\n"
        "(overlay markers = exact tested points only, NOT extrapolated across the grid)",
        y=1.12,
    )
    plt.tight_layout()
    plt.savefig(os.path.join(FIGURES_DIR, "stage15_decision_map.png"), dpi=150, bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Slice 2 -- Robustness under real-world impairments
# ---------------------------------------------------------------------------

def build_robustness_figure(sources: dict):
    stage13 = sources["stage13_multipath"]
    stage10 = sources["stage10_noise"]

    fig, axes = plt.subplots(1, 2, figsize=(13, 5.5))

    # Left: multipath (Stage 13)
    ax = axes[0]
    summary = stage13[stage13.k_db != -999].groupby("k_db").gain_loss_conventional_db.mean().sort_index()
    los_only = stage13[stage13.k_db == -999].gain_loss_conventional_db.mean()
    ax.plot(summary.index, summary.values, marker="o", label="conventional (multipath)")
    ax.axhline(los_only, color="k", linestyle="--", label=f"pure LOS ({los_only:.2f} dB)")
    ax.set_xlabel("Rician K-factor (dB)")
    ax.set_ylabel("Gain loss vs. combined (dB)")
    ax.set_title("Multipath (Stage 13):\nadvantage barely erodes")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)

    # Right: BER at 2 operating points (Stage 10), r_frac=0.05
    ax = axes[1]
    sub = stage10[stage10.r_frac_rayleigh == 0.05]
    operating_points = [-20, -35]
    x = np.arange(len(operating_points))
    width = 0.35
    for i, mode in enumerate(["conventional", "combined"]):
        vals = [sub[(sub.snr_in_db == snr) & (sub.beamformer == mode)].iloc[0].ber
                for snr in operating_points]
        ax.bar(x + (i - 0.5) * width, vals, width, label=mode)
    ax.set_yscale("log")
    ax.set_xticks(x)
    ax.set_xticklabels([f"{snr} dB\n(clean)" if snr == -20 else f"{snr} dB\n(garbage)" for snr in operating_points])
    ax.set_ylabel("BER (QPSK)")
    ax.set_title("Noise (Stage 10):\nsame dB gap, wildly different BER impact")
    ax.legend()
    ax.grid(True, axis="y", alpha=0.3)

    plt.suptitle("Stage 15, Slice 2: The core advantage survives independent real-world impairments", y=1.03)
    plt.tight_layout()
    plt.savefig(os.path.join(FIGURES_DIR, "stage15_robustness.png"), dpi=150, bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Slice 3 -- Bug becomes feature
# ---------------------------------------------------------------------------

def build_bug_to_feature_figure(sources: dict):
    fine_sweep = sources["fine_sweep"]
    stage11 = sources["stage11_multiuser"]

    sub_fs = fine_sweep[(fine_sweep.N == 1024) & (fine_sweep.bandwidth == 2e9)].sort_values("r_frac_rayleigh")
    sub_fs = sub_fs[sub_fs.r_frac_rayleigh.isin([0.02, 0.05, 0.1])]

    sub_mu = stage11[stage11.condition == "B_wideband_combined"].sort_values("r1_frac_rayleigh")

    fig, ax1 = plt.subplots(figsize=(9, 6))
    ax2 = ax1.twinx()

    l1, = ax1.plot(sub_fs.r_frac_rayleigh, sub_fs.gain_loss_conventional_db,
                    "o-", color="firebrick", label="Conventional gain-loss (Stage 5/8, 'bug')")
    l2, = ax2.plot(sub_mu.r1_frac_rayleigh, sub_mu.separation_db,
                    "s-", color="seagreen", label="Multi-user separation (Stage 11, 'feature')")

    ax1.set_xscale("log")
    ax1.set_xlabel("r / Rayleigh distance")
    ax1.set_ylabel("Conventional gain-loss vs. combined (dB)", color="firebrick")
    ax2.set_ylabel("Multi-user separation, combined mode (dB)", color="seagreen")
    ax1.tick_params(axis="y", colors="firebrick")
    ax2.tick_params(axis="y", colors="seagreen")

    ax1.legend(handles=[l1, l2], loc="upper right", fontsize=8)
    plt.title("Stage 15, Slice 3: Same near-field regime, opposite framing\n"
              "(N=1024, deep near-field: worst for single-user angle-only beamforming,\n"
              "best for near-field-aware multi-user range discrimination)")
    plt.tight_layout()
    plt.savefig(os.path.join(FIGURES_DIR, "stage15_bug_to_feature.png"), dpi=150, bbox_inches="tight")
    plt.close(fig)


def build_all_figures(sources: dict):
    os.makedirs(FIGURES_DIR, exist_ok=True)
    build_decision_map(sources)
    build_robustness_figure(sources)
    build_bug_to_feature_figure(sources)